<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="OB-31" ignored="3" name="Test Automation Framework Chrome" tests="1" failures="0" timestamp="18 Nov 2019 12:52:46 GMT" time="17.205" errors="0">
  <testcase name="@BeforeClass runBeforeClass" time="17.067" classname="MDM.Automation_Test.AbstractTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at MDM.Automation_Test.AbstractTest.runBeforeClass(AbstractTest.java:76)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass runBeforeClass -->
  <testcase name="@BeforeMethod runBeforeMethod" time="0.002" classname="MDM.Automation_Test.AbstractTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at MDM.Automation_Test.AbstractTest.runBeforeMethod(AbstractTest.java:84)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod runBeforeMethod -->
  <testcase name="@AfterMethod getResult" time="0.002" classname="MDM.Automation_Test.AbstractTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at MDM.Automation_Test.AbstractTest.getResult(AbstractTest.java:92)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod getResult -->
  <testcase name="@AfterClass runAfterClass" time="0.001" classname="MDM.Automation_Test.AbstractTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at MDM.Automation_Test.AbstractTest.runAfterClass(AbstractTest.java:115)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass runAfterClass -->
  <testcase name="VerifyNewlyCreatedUserCanLogin" time="0.0" classname="MDM.Automation_Test.YourLogoApplicationTests">
    <skipped/>
  </testcase> <!-- VerifyNewlyCreatedUserCanLogin -->
  <testcase name="downloadInvoiceAndVerify" time="0.0" classname="MDM.Automation_Test.YourLogoApplicationTests">
    <ignored/>
  </testcase> <!-- downloadInvoiceAndVerify -->
  <testcase name="addProductToCartAndVerify" time="0.0" classname="MDM.Automation_Test.YourLogoApplicationTests">
    <ignored/>
  </testcase> <!-- addProductToCartAndVerify -->
  <testcase name="VerifyTheSearchResults" time="0.0" classname="MDM.Automation_Test.YourLogoApplicationTests">
    <ignored/>
  </testcase> <!-- VerifyTheSearchResults -->
</testsuite> <!-- Test Automation Framework Chrome -->
